### ISSUE TITLE
Help with otclient knowledge

### ISSUE THREAD

**Issue by alvarobgs** [Blequi/TibiaHardDrive#2]
Hello Bequi, 

So happy to find your profile here on Github!!!

I'm a software developer (mostly from Java world) and also a Tibia player.

I was playing in some random OTServer then I've tought: am I able to create some bot for this just to see how high can I reach?
I've start researching then I found out how amazing and interesting it is, since I'm newbie in C++/C# language, memory address management and reverse engineering in assembly lol

So I've found one gold tutorial of you in TibiaPF that just blow my mind for many possibilities, but unfortunately all that remains from TPForums and TibiaPF is on wayback machine now (like the link below of your post), since they're not online anymore :(
http://web.archive.org/web/20210928112149/https://tibiapf.com/forum/bots-and-cheats/opentibia-clients/otclient/93-otclient-battle-list-tutorial

Do you have any history of the other tutorials? I mean, your explanation was perfect, I learnt a lot reading your post, and I want to keep studying about it, but nowadays is hard to find rich contents like this.

Thank you so far!!

**Comment by Blequi** [comment]
Oh, it is interesting to know that, after almost a decade, there is still people interested on such old reverse engineering content that I wrote in the past.

Back in the time, one of the most valuable piece of information about the Tibia client (9.X era) was TibiaAPI. Recently, I found the repository for [TibiaAPI](https://github.com/ianobermiller/tibiaapi) on Ian's github (he is the guy that kickstarted the TibiaAPI project something like 15 years ago). More or less, structures should follow the content stored there.

In short, I have a few considerations on it all:

* I think it is not worth anymore to invest time on game hacking for Tibia. Even though it is quite interesting, it:
    * consumes so much time to have the true skills to handle it all (4h / day, at least). Back in the time, I used to dedicate 12h + / day on game hacking;
    * there are sparse / small groups of people working with such content. Earlier, there were like 20+ active and experienced game hackers working "together" sharing Tibia RE knowledge on tpforums.
* Probably, high quality content about game hacking for Tibia should be on other game hacking forums like ```unknowncheats```;
* IIRC, [jo3bingham GitHub profile](https://github.com/jo3bingham)  or [jo3bingham otland profile](https://otland.net/members/jo3bingham.6512/) is the tpforums maintainer. You could contact him to know if it is possible to fix tpforums.
* Even though I think that I still have the markup content of my old tutorials saved anywhere in my personal backups, being honest, it is just a very small piece of the whole cake. I mean, there is so much to learn how to reverse engineering that my old tutorials don't cover 1% of would be needed to understand different aspects of the game / client.

**Comment by alvarobgs** [comment]
For sure, your content is rich in knowledge and easy to understand!

I'll take a look in Tibia API project. My goal here is not to hack Tibia client itself, but some otclients just for fun and to challenge myself, and you're so damn right, it takes so many hours for a small piece of progress. 

I'll try to reach him about tpforums, thank you :)
